auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Hnupcfixer's Blog”
title: Mukosame's storys
description: story about hnupcfixer.
url: http://hnupcfixer.github.io
feed: /atom.xml
author_info: <a href="http://hnupcfixer.github.io/">Hnupcfixer</a>
