auto: true

markdown: kramdown

highlighter: 'rouge'
#paginate: 8
permalink: /:title

name: “HNUpcfixer's Blog”
title: HNUpcfixer's storys
description: story about hnupcfixer.
url: http://hnupcfixer.github.io
feed: /feed.xml
author_info: <a href="http://hnupcfixer.github.io/">Hnupcfixer</a>
